# Generated by Django 2.2 on 2019-04-11 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FitnessPlan',
            new_name='HelpfulArticle',
        ),
    ]
